# Generated by Django 2.2.26 on 2022-04-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0002_trackingnumber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingnumber',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackingnumber_order', to='orders.Order'),
        ),
    ]
