# Generated by Django 2.2.26 on 2022-04-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kits', '0003_auto_20220420_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('order_time', models.DateTimeField()),
                ('fulfillment_time', models.DateTimeField()),
                ('cancelled_time', models.DateTimeField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_system', to='orders.OrderSystem')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_kit', to='kits.KitSleeve')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_order', to='orders.Order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_sku', to='kits.Sku')),
            ],
        ),
    ]
